# LSTM with Attention Keras
Rob Trying to make a LSTM with attention

In [2]:
import tensorflow
import keras
import numpy as np
import pandas as pd

from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.callbacks import ModelCheckpoint
from keras.utils import np_utils

# https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

## Data Preprocessing

In [11]:
df = pd.read_csv('../../../Comments_FanofGame.csv')

In [34]:
labels = df['fan_of_team_playing'].values
docs = df['comment_body'].values

vocab_size = 100000
encoded_docs = [one_hot(str(d), vocab_size) for d in docs]

In [39]:
# pad documents to a max length of 500 words
max_length = 100
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

## Create Model

In [43]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=3, verbose=1)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 100, 8)            800000    
_________________________________________________________________
flatten_6 (Flatten)          (None, 800)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 801       
Total params: 800,801
Trainable params: 800,801
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/3
2018028/2018028 [==============================] - 426s 211us/step - loss: 0.6444 - acc: 0.6172
Epoch 2/3
2018028/2018028 [==============================] - 427s 211us/step - loss: 0.6336 - acc: 0.6331
Epoch 3/3
2018028/2018028 [==============================] - 426s 211us/step - loss: 0.6267 - acc: 0.6417
Accuracy: 65.386506


# Glove embeddings

In [58]:
## Use pretraineed glove embeddings

docs_string =[str(doc) for doc in docs]
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs_string)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs_string)
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 100
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# load the whole embedding into memory
embeddings_index = dict()

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[[   4  146  404 ...    0    0    0]
 [   4   14   83 ...    0    0    0]
 [2134   28    6 ...    0    0    0]
 ...
 [   8   66  192 ...    0    0    0]
 [ 250  416  250 ...    0    0    0]
 [  27    2  166 ...    0    0    0]]


In [59]:
f = open('/home/robmulla/Documents/W266/glove/glove.twitter.27B.100d.txt')
for line in f:
    values = line.split()
    word = values[0]
    coefs = asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 1193514 word vectors.


In [61]:
# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector
# define model
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=100, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=3, verbose=1)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=1)
print('Accuracy: %f' % (accuracy*100))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 100, 100)          16079400  
_________________________________________________________________
flatten_10 (Flatten)         (None, 10000)             0         
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 10001     
Total params: 16,089,401
Trainable params: 10,001
Non-trainable params: 16,079,400
_________________________________________________________________
None
Epoch 1/3
2018028/2018028 [==============================] - 59s 29us/step - loss: 0.6936 - acc: 0.5601
Epoch 2/3
2018028/2018028 [==============================] - 58s 29us/step - loss: 0.6927 - acc: 0.5615
Epoch 3/3
2018028/2018028 [==============================] - 34s 17us/step
Accuracy: 56.432369


# Predict?

In [143]:
predict_prob = model.predict(padded_docs)
predictions = model.predict(padded_docs)

In [135]:
model_preds = pd.DataFrame(index=docs_string)

In [148]:
model_preds['predicted_class'] = predictions
model_preds['actual_class'] = labels
model_preds['predic_prob'] = predict_prob
model_preds['prob_off'] = abs(df['predicted_class'] - df['predic_prob'])

In [153]:
df.sort_values('prob_off').head()

predicted_class  \
Pretty sure that was correct as well, nothing n...                1   
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp...                1   
THIS IS RIDICULOUS. \n\n**I would really like a...                1   
Malik Malik Malik Malik Malik Malik Malik Malik...                1   
Commercials, commercials, commercials, Commerci...                0   

                                                    actual_class  \
Pretty sure that was correct as well, nothing n...          True   
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp...          True   
THIS IS RIDICULOUS. \n\n**I would really like a...          True   
Malik Malik Malik Malik Malik Malik Malik Malik...          True   
Commercials, commercials, commercials, Commerci...         False   

                                                     predic_prob      prob_off  
Pretty sure that was correct as well, nothing n...  1.000000e+00  0.000000e+00  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp...  1.000000e+00  0.000000e+00  
THIS IS RIDICULOUS. \n\n**I would really like a...  1.000000e+00  0.000000e+00  
Malik Malik Malik Malik Malik Malik Malik Malik...  1.000000e+00  0.000000e+00  
Commercials, commercials, commercials, Commerci...  6.380873e-17  6.380873e-17

In [155]:
df.sort_values('prob_off').tail(50)

predicted_class  \
Man, really hoping for the best. You never want...                0   
LMAO that Eagles fan "this is our town now"                       1   
Hasnt Crowder done this a few times on fielding...                1   
They'll score on 3rd and 6 anyways                                0   
No responsible Jags fan is cocky at this point.                   1   
Punching people wearing helmets is the stupides...                0   
That fan was the genderbent version of Jason Ga...                1   
someone gonna die climbing those fucking poles                    1   
That should have been Mahomes third TD. The fuc...                0   
Aren't most Dallas Cowboy fans douche nozzles?                    1   
I said in multiple games.                                         1   
Good Lord guys. That was a pretty obvious hold                    1   
(Does he know?)                                                   1   
LMAO at that last play.\n\nAlso, I can't see ho...                0   
Oh fuck yeah!! God this D looks great!!!!                         0   
People angried                                                    1   
"people"                                                          1   
The kicker nightmare will never end                               0   
Yes commissioner                                                  1   
Booyaka! Booyaka!                                                 0   
Holy shit this thread has gone up 1400 comments...                1   
he's fuckn awful                                                  1   
Sean Payton draws up a screen pass better than ...                0   
Because the Bears don't have good players.                        0   
I think it would just be hilarious if the Brown...                1   
Fucking hell. This isn't fair lol                                 1   
omg this crowd is depressing.                                     1   
I'll take a diet Dr. Pepper and some spicy jerk...                0   
That's the game, everybody.                                       0   
Ah, the mighty NFC South.                                         0   
2 more                                                            0   
#2 More                                                           0   
#1 More                                                           0   
1 more!                                                           0   
1  more!!                                                         0   
4 more                                                            0   
14 more                                                           0   
He's good. He'll make it.                                         1   
Stop bailing out Chris Pratt and ginger woman f...                0   
LAAAAAME. I wanted more defense and Romo.                         0   
How many players take a season ending injury an...                1   
This is what you deserve.                                         1   
>AP is the first former MVP winner to play his ...                1   
Head injury on a tackle on kickoff of the game.                   0   
If you have Amazon prime, check out The Grand T...                0   
Women's sports in general                                         0   
That's sports in general                                          0   
Still gotta win tomorrow my dude.                                 1   
get gronk outta there                                             0   
Pratt is so hot right now                                         1   

                                                    actual_class  predic_prob  \
Man, really hoping for the best. You never want...         False     0.499996   
LMAO that Eagles fan "this is our town now"                 True     0.500004   
Hasnt Crowder done this a few times on fielding...         False     0.500004   
They'll score on 3rd and 6 anyways                         False     0.499996   
No responsible Jags fan i

In [142]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_true=df['actual_class'],
                 y_pred=df['predicted_class'])

array([[756944, 347211],
       [531996, 381877]])

# Train LSTM

In [8]:
df = pd.read_csv('../../../Comments_FanofGame.csv')

labels = df['fan_of_team_playing'].values
docs = df['comment_body'].values

## Use pretraineed glove embeddings

docs_string =[str(doc) for doc in docs]
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs_string)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs_string)
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 100
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# load the whole embedding into memory
embeddings_index = dict()

f = open('/home/robmulla/Documents/W266/glove/glove.twitter.27B.100d.txt')
for line in f:
    values = line.split()
    word = values[0]
    coefs = asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector
# define model
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=100, trainable=False)
model.add(e)
#model.add(Flatten())
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

# checkpoint for periodically saving model
filepath="weights-improvement-{epoch:02d}-{val_acc:.2f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=False, mode='max')
callbacks_list = [checkpoint]

# fit the model
model.fit(padded_docs, labels, epochs=8, verbose=1, validation_split=0.33, callbacks=callbacks_list)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=1)
print('Accuracy: %f' % (accuracy*100))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[[   4  146  404 ...    0    0    0]
 [   4   14   83 ...    0    0    0]
 [2134   28    6 ...    0    0    0]
 ...
 [   8   66  192 ...    0    0    0]
 [ 250  416  250 ...    0    0    0]
 [  27    2  166 ...    0    0    0]]
Loaded 1193514 word vectors.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 100, 100)          16079400  
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 16,159,901
Trainable params: 80,501
Non-trainable params: 16,079,400
_________________________________________________________________
None
Train on 1352078 samples, validate on 665950 samples
Epoch 1/8
1352078/1352078 [==============================] - 2003s 1ms/ste

In [13]:
from keras.models import load_model
model = load_model('weights-improvement-08-0.61.hdf5')

In [24]:
predict_prob = model.predict(padded_docs, verbose=1)
predictions = model.predict(padded_docs, verbose=1)

model_preds = pd.DataFrame(index=docs_string)

model_preds['predicted_class'] = predictions
model_preds['actual_class'] = labels
model_preds['predic_prob'] = predict_prob
model_preds['prob_off'] = abs(df['predicted_class'] - df['predic_prob'])

2018028/2018028 [==============================] - 763s 378us/step


KeyError: 'predicted_class'

In [27]:
model_preds.to_csv('Model_Preds_03-29-83.csv')

In [30]:
model_preds['prob_off'] = abs(model_preds['actual_class'] - model_preds['predic_prob'])

In [36]:
model_preds.sort_values('prob_off').head(100)

predicted_class  \
[**@Cianaf**](https://twitter.com/Cianaf/)\n\n>...         0.000393   
[**@Cianaf**](https://twitter.com/Cianaf/)\n\n>...         0.000393   
[**@Cianaf**](https://twitter.com/Cianaf/)\n\n>...         0.000393   
[**@kbaxter11**](https://twitter.com/kbaxter11/...         0.000396   
[**@BrentASJax**](https://twitter.com/BrentASJa...         0.000397   
[**@JakeGiggity**](https://twitter.com/JakeGigg...         0.000407   
[**@guga31bb**](https://twitter.com/guga31bb/)\...         0.000444   
[**@BreakingNNow**](https://twitter.com/Breakin...         0.000473   
[**@Caliboy\_95**](https://twitter.com/Caliboy_...         0.000632   
[**@\_BVM**](https://twitter.com/_BVM/)\n\n> [2...         0.000653   
[**@Advil**](https://twitter.com/Advil/)\n\n> [...         0.000907   
[**@xtinatkacik**](https://twitter.com/xtinatka...         0.001042   
[**@Cianaf**](https://twitter.com/Cianaf/)\n\n>...         0.001303   
[**@CBSSports**](https://twitter.com/CBSSports/...         0.002694   
[**@CBSSports**](https://twitter.com/CBSSports/...         0.002694   
[**@NFL\_Scorigami**](https://twitter.com/NFL_S...         0.002793   
[**@Nick\_PetruZ**](https://twitter.com/Nick_Pe...         0.002834   
[**@PabloTorre**](https://twitter.com/PabloTorr...         0.002918   
[**@NHLFlyers**](https://twitter.com/NHLFlyers/...         0.003011   
[**@NucksHky**](https://twitter.com/NucksHky/)\...         0.003018   
[**@NucksHky**](https://twitter.com/NucksHky/)\...         0.003018   
[**@NucksHky**](https://twitter.com/NucksHky/)\...         0.003018   
[**@Sports\_Burd**](https://twitter.com/Sports_...         0.003032   
[**@FO\_wordofmuth**](https://twitter.com/FO_wo...         0.003040   
[**@FO\_wordofmuth**](https://twitter.com/FO_wo...         0.003040   
[**@gifdsports**](https://twitter.com/gifdsport...         0.003041   
[**@LAXNeddrick**](https://twitter.com/LAXNeddr...         0.003094   
[**@EricStangel**](https://twitter.com/EricStan...         0.003148   
[**@SInow**](https://twitter.com/SInow/)\n\n> [...         0.003165   
[removed]                                                  0.003179   
...                                                             ...   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[removed]                                                  0.003179   
[remo

In [37]:
model_preds.sort_values('prob_off').tail(100)

predicted_class  \
**Please review the rules for [Personal/Fanbase...         0.054451   
**Please review the rules for [Personal/Fanbase...         0.054451   
**Please review the rules for [Personal/Fanbase...         0.054451   
**Please review the rules for [Personal/Fanbase...         0.054451   
**Please review the rules for [Personal/Fanbase...         0.054451   
**Please review the rules for [Political/Religi...         0.054280   
I cannot hate these Jacksonville Jags. I love t...         0.053997   
All these teams getting salty the jags were bea...         0.053851   
Tennessee vs Cleveland looks like an exciting g...         0.053646   
I need to pick up fat Randy in fantasy. If beng...         0.053612   
**Please review the rules for [Political / Reli...         0.053043   
**Please review the rules for [Political / Reli...         0.053043   
**Please review the rules for [Political / Reli...         0.051930   
**Please review the rules for [Political / Reli...         0.051930   
**Please review the rules for [Political / Reli...         0.051930   
Jags vs Pats AFC championship!  I think the jag...         0.051194   
ヽ༼ຈل͜ຈ༽ﾉ Raise Your Bortles ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ R...         0.050235   
What parts are opinions? The Pro Bowls? The sac...         0.951221   
Fire Andy, Alex, Bob burn down Arrowhead sell t...         0.048075   
Watching the Jags drive down the field effortle...         0.046791   
I guess that’s likely better than if it were a ...         0.045523   
> The best running back for the Giants 29th ran...         0.959226   
All right, Sunday night   \nWhere are you?   \n...         0.040629   
You got to see it first hand a few weeks ago. H...         0.960518   
True, but those missed calls happen all the tim...         0.961242   
Seriously, I remember getting well wishes from ...         0.035670   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
...                                                             ...   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
deleted                                                    0.003209   
delet